## Ciência de Dados e Big Data

### Python - Lista de Exercícios 02

#### Rafael Zanini Silveira

8. Usando NumPy, importe o [dataset iris](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data) mantendo o seu conteúdo intacto.

In [99]:
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

print(iris_2d)

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' b'1.5' b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' b'0.3' b'Iris-setosa']
 [b'5.1' b'3.8' b'1.5' b'0.3' b'Iris-setosa']
 [b'5.4' b'3.4' b'1.7' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.7' b'1.5' b'0.4' b'Ir

9. Extraia a coluna *species* do dataset importado na questão anterior para um vetor unidimensional.

In [7]:
species = iris_2d[:,4]

print(species)

[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-versicolor' b'Iris-versicolor'
 b'Iris-versicolor' b'Iris-versicolor' b'Iris-versicolor'
 b'Iris-versicolor' b'Iris-versicolor' b'Iris-versicolor'
 b'Iris-versicolor' b'Iris-versicolor' b'Iris-versicolor'
 b'Iris-versicolor' b'Iri

10. Calcule a média, mediana e desvio padrão da primeira coluna (sepallength) do dataset Iris.

In [12]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

print('Média: ' + str(np.mean(iris_2d[:,0])))
print('Mediana: ' + str(np.median(iris_2d[:,0])))
print('Desvio Padrão: ' + str(np.std(iris_2d[:,0])))

Média: 5.843333333333334
Mediana: 5.8
Desvio Padrão: 0.8253012917851409


11. Normalize a coluna (sepallength) do dataset iris de tal forma que o valor mínimo seja zero (0) e o valor máximo seja 1.

In [23]:
lista = []
Min = min(iris_2d[:,0])
Max = max(iris_2d[:,0])

for i in iris_2d[:,0]:
    lista.append((i-Min)/(Max-Min))

print(lista)

[0.22222222222222213, 0.1666666666666668, 0.11111111111111119, 0.08333333333333327, 0.19444444444444448, 0.30555555555555564, 0.08333333333333327, 0.19444444444444448, 0.027777777777777922, 0.1666666666666668, 0.30555555555555564, 0.13888888888888887, 0.13888888888888887, 0.0, 0.41666666666666663, 0.38888888888888895, 0.30555555555555564, 0.22222222222222213, 0.38888888888888895, 0.22222222222222213, 0.30555555555555564, 0.22222222222222213, 0.08333333333333327, 0.22222222222222213, 0.13888888888888887, 0.19444444444444448, 0.19444444444444448, 0.25000000000000006, 0.25000000000000006, 0.11111111111111119, 0.13888888888888887, 0.30555555555555564, 0.25000000000000006, 0.3333333333333333, 0.1666666666666668, 0.19444444444444448, 0.3333333333333333, 0.1666666666666668, 0.027777777777777922, 0.22222222222222213, 0.19444444444444448, 0.055555555555555594, 0.027777777777777922, 0.19444444444444448, 0.22222222222222213, 0.13888888888888887, 0.22222222222222213, 0.08333333333333327, 0.2777777

12. Encontre o 5º e o 95º percentil do comprimento das pétalas (sepallength) do dataset Iris.

In [32]:
print('5º Percentil: ' + str(np.percentile(iris_2d[:,0], 5)))
print('95º Percentil: ' + str(np.percentile(iris_2d[:,0], 95)))

5º Percentil: 4.6
95º Percentil: 7.254999999999998


13. Encontre a quantidade de valores ausentes, bem como a posição deles da primeira coluna da coluna comprimento das pétalas (sepallength), dentro do vetor abaixo:

In [51]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

lista = list(np.isnan(iris_2d[:,0]))

print('Quantidade de valores ausentes: ' + str(lista.count(True)))
print('Posição dos valores ausentes: ')

for i, valor in enumerate(lista):
    if (valor == True):
        print(i)

Quantidade de valores ausentes: 6
Posição dos valores ausentes: 
12
59
70
103
117
141


14. Filtre o vetor iris_2d do exercício anterior para que ele tenha: (terceira coluna (petallength) > 1.5) && (primeira coluna (sepallength) < 5.0)

In [110]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

condicao = ((iris_2d[:,2] > 1.5) & (iris_2d[:,0] < 5))

print(iris_2d[condicao])

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


15. Selecione as linhas do vetor iris_2d que não contenham valores nan (Not a Number).

In [14]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(3, size=20)] = np.nan

condicao = (np.isnan(iris_2d).any(axis=1))

print(iris_2d[~condicao])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [5.8 4.  1.2 0.2]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.

16. Encontre a correlação entre a primeira coluna (sepallength) e a (terceira coluna (petallength) no vetor iris_2d.

In [47]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

correlacao = np.corrcoef(iris_2d[:,0], iris_2d[:,2])

print('A Correlação é : ' + str(correlacao[0,1]))

A Correlação é : 0.8717541573048718


17. Verifique se o vetor iris_2d possui qualquer valor faltante, caso possui deverá retornar True caso contrário False.

In [54]:
np.isnan(iris_2d).any()

True

18. Substitua todas as ocorrências de nan (Not a Number) por zeros em um vetor NumPy.

In [365]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

np.place(iris_2d, np.isnan(iris_2d), [0])

print(iris_2d)

[[5.1 3.5 1.4 0.2]
 [4.9 0.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0. ]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  0.  0.2]
 [5.7 0.  1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0. ]
 [5.2 3.4 1.4 0. ]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0. ]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [0.  3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 0.  0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

19. Encontre e conte os valores únicos da coluna species

In [370]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

print(np.unique(iris_2d[:,4]))

[b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']


20. Mapeie terceira coluna (petallength) de tal forma que os valores numéricos sejam substituídos por valores textuais, seguindo de acordo com a tabela abaixo:

| Número               | Classificação                
|:---------------------|:--------------|
| Menor do que 3       | Pequena       |
| entre 3 e 5          | Média         |
| Maior ou Igual a 5   | Grande        |

In [222]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

print(iris_2d)

petallength = np.array(iris_2d[:,2], dtype='float')

for i, item in enumerate(petallength):
    if (item < 3):
        iris_2d[i][2] = "Pequena"
    elif (item >= 3 and item < 5):
        iris_2d[i][2] = "Média"
    else:
        iris_2d[i][2] = "Grande"
    
print(iris_2d)

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' b'1.5' b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' b'0.3' b'Iris-setosa']
 [b'5.1' b'3.8' b'1.5' b'0.3' b'Iris-setosa']
 [b'5.4' b'3.4' b'1.7' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.7' b'1.5' b'0.4' b'Ir

21. Crie uma nova coluna chamada *volume*, preenchida com dados resultantes da seguinte equação:

$$volume=\frac{(~ Pi ~x~ Petallength ~x~ Sepal Length^2 ~)}{3}$$

In [263]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

petallength = np.array(iris_2d[:,2], dtype='float')
sepallength = np.array(iris_2d[:,2], dtype='float')
volume = []

for i, item in enumerate(petallength):
    volume.append((np.pi*item*sepallength[i]**2)/3)

iris_2d_volume = np.c_[np.array(iris_2d), np.array(volume)]
    
print(iris_2d_volume)

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa' 2.8735100804834635]
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa' 2.8735100804834635]
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa' 2.3006930199789255]
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa' 3.5342917352885173]
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa' 2.8735100804834635]
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa' 5.144881569028883]
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa' 2.8735100804834635]
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa' 3.5342917352885173]
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa' 2.8735100804834635]
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa' 3.5342917352885173]
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa' 3.5342917352885173]
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa' 4.289321169701265]
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa' 2.8735100804834635]
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa' 1.393819940642672]
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa' 1.8095573684677209]
 [b'5.7' b'4.4' b'1.5' b'0.4

22. Usando NumPy e o dataset iris responda: Qual é o segundo maior valor de comprimento de pétala (petallength) da espécie setosa?

In [264]:
condicao = (iris_2d[:,4] == b'Iris-setosa')

iris_2d_setosa = iris_2d[condicao]
petallength = np.unique(np.sort(iris_2d_setosa[:,2]))

print('Segundo maior Petallength da espécie setosa: ' + str(petallength[len(petallength)-2]))

Segundo maior Petallength da espécie setosa: b'1.7'


23. Ordene o dataset iris com base na coluna sepallength de maneira crescente.

In [265]:
dtype = [('sepallength', float), ('sepalwidth', float), ('petallength', float), ('petalwidth', float), ('species', 'S20')]
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype=dtype)
          
np.sort(iris_2d, order='sepallength')

array([(4.3, 3. , 1.1, 0.1, b'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, b'Iris-setosa'),
       (4.4, 3. , 1.3, 0.2, b'Iris-setosa'),
       (4.4, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.5, 2.3, 1.3, 0.3, b'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, b'Iris-setosa'),
       (4.6, 3.2, 1.4, 0.2, b'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, b'Iris-setosa'),
       (4.6, 3.6, 1. , 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.6, 0.2, b'Iris-setosa'),
       (4.8, 3. , 1.4, 0.1, b'Iris-setosa'),
       (4.8, 3. , 1.4, 0.3, b'Iris-setosa'),
       (4.8, 3.1, 1.6, 0.2, b'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, b'Iris-setosa'),
       (4.8, 3.4, 1.9, 0.2, b'Iris-setosa'),
       (4.9, 2.4, 3.3, 1. , b'Iris-versicolor'),
       (4.9, 2.5, 4.5, 1.7, b'Iris-virginica'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, b'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, b'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, b'Iris-setosa'),
   

24. Encontre o valor mais frequente da terceira coluna (petallength) do dataset iris.

In [331]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

valores, contador = np.unique(iris_2d[:,2], return_counts=True)

posicao = np.where(contador == contador.max())

print('O valor mais frequente da coluna Petallength é: ' + str(valores[int(posicao[0])]))

O valor mais frequente da coluna Petallength é: b'1.5'


25. Encontre a posição da primeira ocorrência de um valor maior do que 1.0 da quarta coluna (petalwidth) do dataset iris.

In [343]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

posicao = np.where(iris_2d[:,3] > 1)
list_posicao = list(posicao[0])

print('A posição da primeira ocorrencia de valor maior que 1 é: ' + str(int(list_posicao[0])))

A posição da primeira ocorrencia de valor maior que 1 é: 50


26. Obtenha a posição dos top 5 valores maíximos do vetor abaixo:

In [353]:
np.random.seed(100)
vetor = np.random.uniform(1,50, 20)

print(vetor[np.argsort(vetor)[-5:]])

[40.99501269 41.466785   42.39403048 44.67477576 48.95256545]


27. Encontre a média de uma coluna numérica agrupada por uma coluna categórica em uma matriz (vetor numpy 2D)

In [112]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

iris_2d_setosa = iris_2d[iris_2d[:,4]==b'Iris-setosa']
iris_2d_versicolor = iris_2d[iris_2d[:,4]==b'Iris-versicolor']
iris_2d_virginica = iris_2d[iris_2d[:,4]==b'Iris-virginica']

sepallength_setosa = np.array(iris_2d_setosa[:,0], dtype='float')
sepallength_versicolor = np.array(iris_2d_versicolor[:,0], dtype='float')
sepallength_virginica = np.array(iris_2d_virginica[:,0], dtype='float')

species = np.array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'])
media = np.array([sepallength_setosa.mean(), sepallength_versicolor.mean(), sepallength_virginica.mean()])

print(np.c_[species, media])

[[b'Iris-setosa' b'5.006']
 [b'Iris-versicolor' b'5.936']
 [b'Iris-virginica' b'6.587999999999998']]
